trigger: 
  branches:
    include:
      - '*'
    exclude:
      - develop
      - master
      - azure-pipelines

pool: Default

name: $(Year:yyyy).$(Minor)$(Rev:.r)-quickCI

variables:
- group: versioning
- name: 'solution' 
  value: 'PasswordManagement.sln'
- name: 'buildPlatform' 
  value: 'Any CPU'
- name: 'buildConfiguration'
  value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: VSBuild@1
  displayName: 'Restore Solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '-t:restore'
    maximumCpuCount: true
    
- task: VSBuild@1
  displayName: 'Restore and Build'
  inputs:
    solution: '$(solution)'
    maximumCpuCount: true