# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool: 
  vmImage: windows-latest

name: $(Major).$(Minor)$(Rev:.r)

variables:
- group: passwordmanagement
- group: versioning
- name: solution
  value: $(pwmSolution)
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DownloadSecureFile@1
  name: deploy
  inputs:
    secureFile: 'Deploy.zip'

- task: ExtractFiles@1
  displayName: Extract Deploy tool
  inputs:
    archiveFilePatterns: '$(deploy.secureFilePath)'
    destinationFolder: '$(Agent.TempDirectory)\Deploy'
    cleanDestinationFolder: true
    overwriteExistingFiles: false

- task: DotNetCoreCLI@2
  displayName: Restore solution
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\REFame.PasswordManagement\REFame.PasswordManagement.App.csproj'
    arguments: '-c Release -r win-x64 -o $(Build.ArtifactStagingDirectory)\App -p:Version=$(Build.BuildNumber)'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: 'test'
    arguments: '-s .runsetting'
    projects: '$(solution)'
    includeNuGetOrg: true

- task: CmdLine@1
  displayName: Run Deploy.exe
  inputs:
    filename: '$(Agent.TempDirectory)\Deploy\Deploy.exe'
    arguments: '-l $(Build.ArtifactStagingDirectory)\App -v $(Build.BuildNumber) -t $(Agent.TempDirectory)\DeployTemp -w  $(Build.SourcesDirectory)\REFame.PasswordManagement -o $(Build.ArtifactStagingDirectory)\Setup'

- task: PowerShell@2
  displayName: Rename Setup.exe
  inputs:
    targetType: 'inline'
    script: 'Rename-Item -Path "$(Build.ArtifactStagingDirectory)\Setup\Setup.exe" -NewName "Setup-$(Build.BuildNumber).exe"'
    failOnStderr: true
    showWarnings: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Setup\RELEASES'
    ArtifactName: 'setup-package'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Setup\Setup-$(Build.BuildNumber).exe'
    ArtifactName: 'setup'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Setup\PASSWORDMANAGEMENT-$(Build.BuildNumber)-full.nupkg'
    ArtifactName: 'setup-package'
    publishLocation: 'Container'
