# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr: none
trigger: none

schedules:
  - cron: '0 0 * * *'
    displayName: midnight build
    branches:
      include:
        - master
        - develop
    always: true

pool: Default

name: $(Year:yyyy).$(MinorVersion)$(Rev:.r)-nightly

variables:
  solution: 'PasswordManagement.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Install Microsoft Test platform'
  inputs:
    packageFeedSelector: nugetOrg
    versionSelector: latestStable

- task: NuGetAuthenticate@0
  displayName: 'Authtification'
  inputs:
   forceReinstallCredentialProvider: true

- checkout: self

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '**Tests/*.csproj'
    platform: 'AnyCPU'
    configuration: '$(buildConfiguration)'
- task: VSTest@2
  displayName: 'Run Unit Tests'
  inputs:
    testSelector: testAssemblies
    testAssemblyVer2: |
      **\*Tests.dll
      **\*test.dll
      !**\*TestAdapter.dll
      !**\obj\**
    codeCoverageEnabled: true
    diagnosticsEnabled: true
    vsTestVersion: toolsInstaller

- task: ResharperCli@2
  displayName: 'Resharper check coding guidelines'
  inputs:
    solutionOrProjectPath: '$(solution)'
    failBuildLevelSelector: 'Error'
    additionalArguments: '--exclude=**.Tests/**/*.cs;**Resources/**/*.*;**.Test/**/*.cs;**/**/*.xaml'
