# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool: Default

name: $(Year:yyyy).$(MinorVersion)$(Rev:.r)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

- task: VSBuild@1
  displayName: 'Restore Solution'
  inputs:
    solution: 'PasswordManagement.sln'
    msbuildArgs: '-t:restore'
    maximumCpuCount: true

- task: VSBuild@1
  displayName: 'Build Solution to ArtifactStagingDirectory'
  inputs:
    solution: PasswordManagement.sln
    msbuildArgs: '/p:OutDir=$(Build.ArtifactStagingDirectory)/App'

- task: VSBuild@1
  displayName: 'Build Test-Projects'
  inputs:
    solution: '**Tests/*.csproj'
    platform: 'AnyCPU'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run Unit Tests'
  continueOnError: True
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\** 
    codeCoverageEnabled: True
    diagnosticsEnabled: True
    vsTestVersion: 'toolsInstaller'

# - task: DotNetCoreCLI@2
#   displayName: Run Unit Tests
#   inputs:
#     command: 'test'
#     projects:  |
#       **/*.csproj

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

