pr: none
trigger: none

schedules:
  - cron: '0 12 * * *'
    displayName: midnight build
    branches:
      include:
        - master
        - develop

pool: 
  vmImage: windows-latest

name: $(Major).$(Minor)$(Rev:.r)-nightly

variables:
- group: passwordmanagement
- group: versioning
- name: solution 
  value: $(pwmSolution)
- name: buildPlatform 
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

jobs:
- job: 
  displayName: Run Unit Tests
  steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2 
    displayName: 'Run Unit Tests and collect coverage'
    inputs:
      arguments: -c $(BuildConfiguration) --collect:"XPlat Code Coverage" -- RunConfiguration.DisableAppDomain=true
      command: 'test'
      projects: '$(solution)'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish coverage results'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
      pathToSources: '$(Build.SourcesDirectory)'

- job:
  displayName: Run Resharper
  steps:

  - task: DotNetCoreCLI@2
    displayName: Create new tool manifest
    inputs:
      command: 'custom'
      custom: 'new'
      arguments: 'tool-manifest'

  - task: DotNetCoreCLI@2
    displayName: 'Install Resharper global tool'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install JetBrains.ReSharper.GlobalTools'

  - task: DotNetCoreCLI@2
    displayName: 'Resharper check coding guidelines'
    inputs:
      command: 'custom'
      custom: 'jb'
      arguments: 'inspectcode -o="$(Build.ArtifactStagingDirectory)\report.xml" $(solution) -s="INFO" --exclude=**/*.dll;**/**/*.xaml'

  - task: PublishBuildArtifacts@1 
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\report.xml'
      ArtifactName: 'Resharper'
      publishLocation: 'Container'