trigger: 
  branches:
    include:
      - '*'
    exclude:
      - develop
      - master

pool: Default

name: $(Year:yyyy).$(Minor)$(Rev:.r)-quickCI

variables:
- group: versioning
- name: 'solution' 
  value: '**/*.csproj'
- name: 'buildPlatform' 
  value: 'Any CPU'
- name: 'buildConfiguration'
  value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@0
  displayName: 'Authtification'
  inputs:
   forceReinstallCredentialProvider: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'a4524e36-84b7-4bc9-945a-1d40199dd038'

- task: VSBuild@1
  displayName: 'Restore and Build'
  inputs:
    solution: '$(solution)'
    maximumCpuCount: true