# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr: none
trigger: none

schedules:
  - cron: '0 0 * * *'
    displayName: midnight build
    branches:
      include:
        - master
        - develop
    always: true

pool: 
  vmImage: 'ubuntu-latest'

name: $(Year:yyyy).$(MinorVersion)$(Rev:.r)-nightly

variables:
  solution: 'PasswordManagement.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: NuGetAuthenticate@0
  displayName: 'Authtification'
  inputs:
   forceReinstallCredentialProvider: true

- checkout: self
  displayName: 'Checkout source-code'

- task: NuGetCommand@2
  displayName: 'Restore Solution'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2 
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(solution)'

- task: ResharperCli@2
  displayName: 'Resharper check coding guidelines'
  inputs:
    solutionOrProjectPath: '$(solution)'
    failBuildLevelSelector: 'Error'
    additionalArguments: '--exclude=**.Tests/**/*.cs;**Resources/**/*.*;**.Test/**/*.cs;**/**/*.xaml'
