//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REFame.PasswordManagement.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REFame.PasswordManagement.Localization.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string AddPassword_LabelComment_Content {
            get {
                return ResourceManager.GetString("AddPassword_LabelComment_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AddPassword_LabelDescription_Content {
            get {
                return ResourceManager.GetString("AddPassword_LabelDescription_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AddPassword_LabelPassword_Content {
            get {
                return ResourceManager.GetString("AddPassword_LabelPassword_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser_LabelAddUser_Content {
            get {
                return ResourceManager.GetString("AddUser_LabelAddUser_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AddUser_LabelPassword_Content {
            get {
                return ResourceManager.GetString("AddUser_LabelPassword_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string AddUser_LabelRepeatPassword_Content {
            get {
                return ResourceManager.GetString("AddUser_LabelRepeatPassword_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AddUser_LabelUser_Content {
            get {
                return ResourceManager.GetString("AddUser_LabelUser_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AddUser_LabelUsername_Content {
            get {
                return ResourceManager.GetString("AddUser_LabelUsername_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter credentials.
        /// </summary>
        public static string Login_LabelEnterCredentials_Content {
            get {
                return ResourceManager.GetString("Login_LabelEnterCredentials_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_LabelLogin_Content {
            get {
                return ResourceManager.GetString("Login_LabelLogin_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_LabelPassword_Content {
            get {
                return ResourceManager.GetString("Login_LabelPassword_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_LabelUsername_Content {
            get {
                return ResourceManager.GetString("Login_LabelUsername_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordManagement {0} (en-en).
        /// </summary>
        public static string MainWindow_ctor_Title {
            get {
                return ResourceManager.GetString("MainWindow_ctor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string MainWindow_Grid_Comment_Header {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Comment_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MainWindow_Grid_Description_Header {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Description_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MainWindow_Grid_Password_Header {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Password_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string MainWindow_Grid_ShowPassword_Header {
            get {
                return ResourceManager.GetString("MainWindow_Grid_ShowPassword_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MainWindow_LabelDelete_Content {
            get {
                return ResourceManager.GetString("MainWindow_LabelDelete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainWindow_LabelEdit_Content {
            get {
                return ResourceManager.GetString("MainWindow_LabelEdit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_LabelOpenSettings_Content {
            get {
                return ResourceManager.GetString("MainWindow_LabelOpenSettings_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-management.
        /// </summary>
        public static string MainWindow_LabelOpenUserManagement_Content {
            get {
                return ResourceManager.GetString("MainWindow_LabelOpenUserManagement_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MainWindow_LabelTextAdd_Content {
            get {
                return ResourceManager.GetString("MainWindow_LabelTextAdd_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading updates.
        /// </summary>
        public static string ProgressBar_LabelTitle_Content_Downloading {
            get {
                return ResourceManager.GetString("ProgressBar_LabelTitle_Content_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing updates.
        /// </summary>
        public static string ProgressBar_LabelTitle_Content_Installing {
            get {
                return ResourceManager.GetString("ProgressBar_LabelTitle_Content_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SettingsView_LabelRestartRequired_Content {
            get {
                return ResourceManager.GetString("SettingsView_LabelRestartRequired_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI-Color.
        /// </summary>
        public static string ThemeSettings_LabelColor_Content {
            get {
                return ResourceManager.GetString("ThemeSettings_LabelColor_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ThemeSettings_LabelLanguage_Content {
            get {
                return ResourceManager.GetString("ThemeSettings_LabelLanguage_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeSettings_LabelTheme_Content {
            get {
                return ResourceManager.GetString("ThemeSettings_LabelTheme_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string UserManagementView_Label_Name_Content {
            get {
                return ResourceManager.GetString("UserManagementView_Label_Name_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string UserManagementView_Label_UserName_Content {
            get {
                return ResourceManager.GetString("UserManagementView_Label_UserName_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Window_LabelCancel_Content {
            get {
                return ResourceManager.GetString("Window_LabelCancel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Window_LabelSave_Content {
            get {
                return ResourceManager.GetString("Window_LabelSave_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Window_No {
            get {
                return ResourceManager.GetString("Window_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Window_Yes {
            get {
                return ResourceManager.GetString("Window_Yes", resourceCulture);
            }
        }
    }
}
